MODULE := archive
ROOT_DIR := ../..

INCLUDE_DIR  = 
INCLUDE_DIR += .
INCLUDE_DIR += $(ROOT_DIR)/src/common

SOURCES  = 
SOURCES += rle.c

include $(ROOT_DIR)/mk/defs.mk

.PHONY: all
all: $(TARGET_LIB)

include $(ROOT_DIR)/mk/rules-lib.mk

