MODULE := memory
ROOT_DIR := ../..

INCLUDE_DIR  = 
INCLUDE_DIR  = .
INCLUDE_DIR += $(ROOT_DIR)/src/common

SOURCES  = 
SOURCES += fixed_memorypool.c
# SOURCES += memorypool.c

include $(ROOT_DIR)/defs.mk
include $(ROOT_DIR)/rules.mk

